[workspace]
resolver = "3"
members = ["crates/rubrica-type", "crates/rubrica-app", "crates/rubrica-doc", "crates/rubrica-math", "crates/rubrica-workspace"]

[workspace.package]
version = "0.3.1"
edition = "2021"
rust-version = "1.95"
license = "MIT OR Apache-2.0"
repository = "https://github.com/LiJiaHua1024/rubrica"

[workspace.dependencies]
rubrica-type = { path = "crates/rubrica-type" }
rubrica-doc = { path = "crates/rubrica-doc" }
rubrica-math = { path = "crates/rubrica-math" }
rubrica-workspace = { path = "crates/rubrica-workspace" }
unicode-linebreak = "0.1"
unicode-script = "0.5"

[profile.release]
lto = "thin"
codegen-units = 1
