[workspace]
resolver = "3"
members = ["crates/rubrica-type", "crates/rubrica-app"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
rubrica-type = { path = "crates/rubrica-type" }
unicode-linebreak = "0.1"
unicode-script = "0.5"

[profile.release]
lto = "thin"
codegen-units = 1
